/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-04-09 09:20:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.auth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class functionInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<html><head>\r\n");
      out.write("<base href=\"");
      out.print(basePath );
      out.write("\" />\r\n");
      out.write("    <title>功能维护</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/jquery-ui.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.2.min.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deletefunction(){\r\n");
      out.write("\t\tvar flag = false;\r\n");
      out.write("\t\tvar temp = document.getElementsByName(\"selectid\"); \r\n");
      out.write("\t\tfor (var i =0; i<temp.length; i++) { \r\n");
      out.write("\t\t\tif(temp[i].checked){\r\n");
      out.write("\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t    break;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(flag){ \r\n");
      out.write("\t\t\tvar cf = confirm(\"是否确定删除功能？\");\r\n");
      out.write("\t\t\tif(cf==true){\r\n");
      out.write("\t\t\t\tvar pm_delete_role = new PostManager('functionAction/deleteFunction');\r\n");
      out.write("\t\t\t\tvar params = {'functionId' : $(\"input:radio[name=selectid]:checked\").val()};\r\n");
      out.write("\t\t\t\tpm_delete_role.post(params).complete = function() {\r\n");
      out.write("\t\t\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\talert(\"请选择要删除的功能！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction addfunction(){\r\n");
      out.write("\t\tvar pm_rr = new PostManager('pageAction/toEditFunction');\r\n");
      out.write("\t\tpm_rr.post().complete = function(data) {\r\n");
      out.write("\t\t\tparent.rightFrame.location.href = $(\"#basePath\").val() + data.url;\r\n");
      out.write("\t\t};\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction queryFunction(){\r\n");
      out.write("\t\tquery(1);\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction editfunction(){\r\n");
      out.write("\t\tvar flag = false;\r\n");
      out.write("\t\tvar temp = document.getElementsByName(\"selectid\"); \r\n");
      out.write("\t\tfor (var i =0; i<temp.length; i++) { \r\n");
      out.write("\t\t\tif(temp[i].checked){\r\n");
      out.write("\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\t   break;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(flag){ \r\n");
      out.write("\t\t\tvar pm_rr = new PostManager('pageAction/toEditFunction');\r\n");
      out.write("\t\t\tpm_rr.post().complete = function(data) {\r\n");
      out.write("\t\t\t\tparent.rightFrame.location.href = $(\"#basePath\").val() + data.url+'?functionId='+$(\"input:radio[name=selectid]:checked\").val();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\talert(\"请选择要修改的功能！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showFunctions(data) {\r\n");
      out.write("\t\t$('#tBody').empty();\r\n");
      out.write("\t\t$.each(data, function(){\r\n");
      out.write("\t\t\tvar tbodyHtml = '<tr height=\"20\">'\r\n");
      out.write("\t\t\t\t+ '<td height=\"20\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\">&nbsp;'\r\n");
      out.write("\t\t\t\t+ '<input type=\"radio\" name=\"selectid\" value=\"'+this.id+'\" align=\"center\" ></td>'\r\n");
      out.write("\t\t\t\t+ '<td height=\"20\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" align=\"center\" >'\r\n");
      out.write("\t\t\t\t+ '&nbsp;'+this.functionName+'</td>'\r\n");
      out.write("\t\t\t\t+ '<td height=\"20\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" align=\"center\" >'\r\n");
      out.write("\t\t\t\t+ '&nbsp;'+(this.pName != null ? this.pName : '')+'</td>'\r\n");
      out.write("\t\t\t\t+ '<td height=\"20\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" align=\"center\" >'\r\n");
      out.write("\t\t\t\t+ '&nbsp;'+(this.orderNum != null ? this.orderNum : '')+'</td>'\r\n");
      out.write("\t\t\t\t+ '<td height=\"20\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" align=\"center\" >'\r\n");
      out.write("\t\t\t\t+ '&nbsp;'+(this.functionUrl != null ? this.functionUrl : '')+'</td>'\r\n");
      out.write("\t\t\t\t+ '<td height=\"20\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" align=\"center\" >'\r\n");
      out.write("\t\t\t\t+ '&nbsp;'+(this.functionDesc != null ? this.functionDesc : '')+'</td></tr>';\r\n");
      out.write("\t\t\t$('#tBody').append(tbodyHtml);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction query(cp) {\r\n");
      out.write("\t\tvar params = {'functionName' : $(\"#selectid\").val(), \"pageBean.currentPage\" : cp, 'isPagination' : true};\r\n");
      out.write("\t\tvar pm_r = new PostManager('functionAction/findByName');\r\n");
      out.write("\t\tpm_r.post(params).complete = function(data) {\r\n");
      out.write("\t\t\t$('#tBody').empty();\r\n");
      out.write("\t\t\t$(\"#pageBody\").empty();\r\n");
      out.write("\t\t\tshowFunctions(data.result);\r\n");
      out.write(" \t\t\t$(\"#pageBody\").html(pm_r.getPageHtml(data));\r\n");
      out.write("\t\t};\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tqueryFunction();\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"hidden\" id=\"basePath\" value=\"");
      out.print(basePath );
      out.write("\">\r\n");
      out.write("\t<table width=\"100%\" align=\"center\" style=\"border:1px solid #a6c9e2;font-size:13px;\">\r\n");
      out.write("\t \t\t<tbody><tr>\t \t\t\t\r\n");
      out.write("\t \t\t\t<td align=\"left\">\r\n");
      out.write("\t \t\t\t\t<input type=\"button\" id=\"addid\" value=\"新增\" onclick=\"addfunction()\">&nbsp;\r\n");
      out.write("\t \t\t\t\t<input type=\"button\" id=\"deleteid\" value=\"删除\" onclick=\"deletefunction()\">&nbsp;\r\n");
      out.write("\t \t\t\t\t<input type=\"button\" id=\"editid\" value=\"修改\" onclick=\"editfunction()\">&nbsp;\r\n");
      out.write("\t \t\t\t\t<font color=\"#FF0000\">\r\n");
      out.write("\t \t\t\t\t</font>\r\n");
      out.write("\t \t\t\t</td>\r\n");
      out.write("\t \t\t\t<td align=\"left\">\r\n");
      out.write("\t \t\t\t\t功能名称&nbsp;<input type=\"text\" id=\"selectid\" name=\"functionName\" style=\"width:200px;\">&nbsp;\r\n");
      out.write("\t \t\t\t\t<input type=\"button\" id=\"query\" value=\"查询\" onclick=\"queryFunction()\">&nbsp;\r\n");
      out.write("\t \t\t\t</td>\r\n");
      out.write("\t \t\t</tr>\r\n");
      out.write("\t</tbody></table>  \r\n");
      out.write("\t<br>\r\n");
      out.write("\t<table style=\"width:100%;height:100%;border-top:1px solid #a6c9e2;border-left:1px solid #a6c9e2;border-right:1px solid #a6c9e2;font-size:13px;\" border=\"0\" align=\"center\" cellpadding=\"1\" cellspacing=\"0\">\r\n");
      out.write("\t\t<tr height=\"20\">\r\n");
      out.write("\t\t\t<td width=\"5%\" bgcolor=\"#eaf4fd\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" height=\"20\" align=\"center\">\r\n");
      out.write("\t\t\t&nbsp;操作\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"12%\" bgcolor=\"#eaf4fd\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" height=\"20\" align=\"center\">\r\n");
      out.write("\t\t\t&nbsp;功能名称\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"12%\" bgcolor=\"#eaf4fd\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" height=\"20\" align=\"center\">\r\n");
      out.write("\t\t\t&nbsp;父节点名称 \r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"5%\" bgcolor=\"#eaf4fd\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" height=\"20\" align=\"center\">\r\n");
      out.write("\t\t\t&nbsp;节点序号\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"36%\" bgcolor=\"#eaf4fd\" style=\"border-bottom:1px solid #a6c9e2;border-right:1px solid #a6c9e2;\" height=\"20\" align=\"center\">\r\n");
      out.write("\t\t\t&nbsp;功能链接\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"20%\" bgcolor=\"#eaf4fd\" style=\"border-bottom:1px solid #a6c9e2;\" height=\"20\" align=\"center\">\r\n");
      out.write("\t\t\t&nbsp;功能描述\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tbody id=\"tBody\">\r\n");
      out.write("\t\t</tbody></table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table width=\"100%\" height=\"30\" border=\"0\" align=\"center\">\r\n");
      out.write("\t\t\t<tbody id=\"pageBody\"></tbody></table>\r\n");
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
