/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-04-09 09:20:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"Bookmark\" href=\"images/icon32.ico\">\r\n");
      out.write("    <link rel=\"Shortcut Icon\" href=\"images/icon32.ico\"/>\r\n");
      out.write("  \t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("    <title>东航金融物网风险管理业务管理系统</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/jquery-ui.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\"/>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\thtml body{ margin:0; padding:0; width:100%; font-size:12px;color: #737373; background:#FFF}\r\n");
      out.write("\t\tp{margin:0}\r\n");
      out.write("\t\ta:link{color: #737373;text-decoration: none}\r\n");
      out.write("\t\ta:visited{color:#737373;text-decoration: none}\r\n");
      out.write("\t\ta:hover{color:#0e61b6;text-decoration: none}\r\n");
      out.write("\t\ta:active{color:#0e61b6;text-decoration: none}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.11.2.min.js\"></script>  \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.form.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tif(top.location!=self.location){\r\n");
      out.write("\t\t\ttop.location=self.location;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('#changepassworddialog').dialog({\r\n");
      out.write("\t\t\t\tautoOpen: false,\r\n");
      out.write("\t\t\t\twidth: 500,\r\n");
      out.write("\t\t\t\theight:300,\r\n");
      out.write("\t\t\t\tmodal:true,\r\n");
      out.write("\t\t\t\tresizable:false\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tlistDepartments();\r\n");
      out.write("\t\t\t$(\"#loginForm_id\").ajaxForm({\r\n");
      out.write("\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\turl:'employeeAction/login',\r\n");
      out.write("\t\t\t\tbeforeSubmit:showRequest,\r\n");
      out.write("\t\t\t\tcontentType:'application/x-www-form-urlencoded;charset=utf-8',\r\n");
      out.write("\t\t\t\tsuccess:showResponseResult\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#btnsubmit_id').click(function(){\r\n");
      out.write("\t\t\t\tif($(\"#oldpwd_id\").val()==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入旧密码！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#newpwd_id\").val()==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入新密码！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#cinfirmnewpwd_id\").val()==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入确认新密码！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#newpwd_id\").val()!=$(\"#cinfirmnewpwd_id\").val()){\r\n");
      out.write("\t\t\t\t\talert(\"新密码和确认新密码不一致！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar re=/[A-Za-z].*[0-9]|[0-9].*[A-Za-z]/;\r\n");
      out.write("\t            if(!re.test($(\"#newpwd_id\").val())){\r\n");
      out.write("\t             \talert(\"密码必须是数字和字母的组合\");\r\n");
      out.write("\t                  return false;\r\n");
      out.write("\t            }\r\n");
      out.write("\t           \r\n");
      out.write("\t            var pm_c = new PostManager('employeeAction/changePwd');\r\n");
      out.write("\t            var data = { \r\n");
      out.write("\t\t\t\t\t\toldpwd:$(\"#oldpwd_id\").val(),\r\n");
      out.write("\t\t\t\t\t\tnewpwd:$(\"#newpwd_id\").val()\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t            pm_c.post(data).complete = function(data){\r\n");
      out.write("\t            \tif(data.status==\"success\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"修改成功，请记住您的密码，重新登录系统！\");\r\n");
      out.write("\t\t\t\t\t\t$('#changepassworddialog').dialog('close');\r\n");
      out.write("\t\t\t\t\t}else if(data.status==\"error\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"旧密码错误！\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"保存失败！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t            };\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#login\").click(function(){\r\n");
      out.write("\t\t\t\t$(\"#loginForm_id\").submit();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#resetid\").click(function(){\r\n");
      out.write("\t\t\t\t$(\"#username_id\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"#password_id\").val(\"\")\r\n");
      out.write("\t\t\t\tvar pm_out = new PostManager('employeeAction/logout');\r\n");
      out.write("\t            pm_out.post();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction showRequest(formData,jqForm,options){\r\n");
      out.write("\t\t\tif($(\"#username_type\").val() == 'role_-1'){\r\n");
      out.write("\t\t\t\talert(\"请选择用户类型\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($(\"#username_id\").val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"请输入用户名\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($(\"#password_id\").val()==\"\"){\r\n");
      out.write("\t\t\t\talert(\"请输入密码\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction showResponseResult(data){\r\n");
      out.write("\t\t\tif(data.status==\"success\"){\r\n");
      out.write("\t\t\t\tlocation.href = \"employeeAction/main\";\r\n");
      out.write("\t\t\t}else if(data.status==\"fail\"){\r\n");
      out.write("\t\t\t\talert(\"您的用户名还没有配置好,请联系系统管理员！\");\r\n");
      out.write("\t\t\t}else if(data.status==\"error\"){\r\n");
      out.write("\t\t\t\talert(\"用户名或密码错误！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction listDepartments() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    \t\tvar pm_company_departments = new PostManager('departmentAction/listDepartments');\r\n");
      out.write("\t    \t\tvar params = {'companyId' : 1};\r\n");
      out.write("\t    \t\tpm_company_departments.post(params).complete = function(data){\r\n");
      out.write("\t    \t\t\tvar optionHtml = '<option value=\"0\">请选择</option><option value =\"role_0\">管理员</option>';\r\n");
      out.write("\t    \t\t\t$.each(data, function(){\r\n");
      out.write("\t    \t\t\t\toptionHtml += '<option value=\"'+this.id+'\">'+this.departmentName+'</option>';\r\n");
      out.write("\t    \t\t\t});\r\n");
      out.write("\t    \t\t\t$(\"select[name='userType']\").html(optionHtml);\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction monitor(event){\r\n");
      out.write("\t\t    var code,tag;\r\n");
      out.write("\t\t    if(!event){\r\n");
      out.write("\t\t        event = window.event;\r\n");
      out.write("\t\t        //target = event.srcElement;\r\n");
      out.write("\t\t        code = event.keyCode;\r\n");
      out.write("\t\t        if(code==13){\r\n");
      out.write("\t\t            $(\"#login\").trigger(\"click\");\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }else{\r\n");
      out.write("\t\t        target = event.target;\r\n");
      out.write("\t\t        code = event.keyCode;\r\n");
      out.write("\t\t        if(code==13){\r\n");
      out.write("\t\t            $(\"#login\").trigger(\"click\");\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write(" \r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"loginForm\" id=\"loginForm_id\" method=\"post\" action=\"/employeeAction/login\">\r\n");
      out.write("<div style=\"height:28px; background:#e2e2e2\">\r\n");
      out.write("\t<div style=\"width:1024px; line-height:28px; margin-left:auto; margin-right:auto\">\r\n");
      out.write("      <div style=\"float:left; width:800px\"><a href=\"http://www.kiiik.com\" target=\"_blank\">东航金控</a> | <a href=\"http://www.cesfinance.com\" target=\"_blank\">东航财务</a> | <a href=\"http://www.cescapital.com\" target=\"_blank\">东航金融（香港</a>） |  <a href=\"http://www.99fund.com\" target=\"_blank\">汇添富基金</a> | <a href=\"http://www.air-union.com/\" target=\"_blank\">航联保险</a> | <a href=\"http://www.lhmj.org\" target=\"_blank\">蓝海密剑</a> | <a href=\"http://forum.kiiik.com\" target=\"_blank\">官方论坛</a></div>\r\n");
      out.write("      <div style=\"float:right\"><a href=\"http://oa.kiiik.com\" target=\"_blank\">OA系统</a> | <a href=\"http://mail.kiiik.com\" target=\"_blank\">邮箱</a> | <a href=\"http://aaa.kiiik.com\" target=\"_blank\">增值服务中心</a> | <label id=\"resetid\" style=\"cursor:pointer;\">重置</label></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:100%; height:164px; background:#FFF; vertical-align:bottom\">\r\n");
      out.write("\t<div style=\"width:1024px; line-height:28px; margin-left:auto; margin-right:auto\"><img src=\"images/logo.gif\" width=\"543\" height=\"164\" /></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:100%; height:572px; background:#FFF url(images/bg.jpg) center\">\r\n");
      out.write("<!--控制距离-->\r\n");
      out.write("\t<div style=\"width:1024px; height:436px; margin-left:auto; margin-right:auto\">\r\n");
      out.write("     <!--控制透明度-->\r\n");
      out.write("    \t<div style=\"width:306px; height:266px; float:left; margin:63px 0px auto 702px; padding:25px 40px 40px 40px; color:#FFF;display:inline\">\r\n");
      out.write("        \r\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td height=\"25\">公司</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    <select name=\"company\" id=\"username_type\" style=\"width:225px; height:25px;line-height: 25px; border:0px; color: Gray; background:#FFF\" disabled=\"disabled\"/>\r\n");
      out.write("\t \t\t<option>东航物网风险管理子公司</option>\r\n");
      out.write("\t </select>\r\n");
      out.write("     </td>\r\n");
      out.write("  </tr>     \r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"25\">账户部门</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    <select name=\"userType\" id=\"username_type\" style=\"width:225px; height:25px;line-height: 25px; border:0px; color: Gray; background:#FFF\">\r\n");
      out.write("\t \t\t\t\t\t\r\n");
      out.write("\t </select>\r\n");
      out.write("     </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"25\">账户名</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><input type=\"text\" name=\"userName\" value=\"\" id=\"username_id\" style=\"width:225px; height:25px;line-height: 25px; border:0px; color:#acabab; background:#FFF\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" \r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"20\">密码</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><input type=\"password\" name=\"password\" value=\"\" onkeydown=\"monitor(event)\" id=\"password_id\" style=\"width:225px; height:25px;line-height: 25px; border:0px; color:#acabab;background:#FFF\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"5\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><input name=\"submitbutton\" type=\"button\" id=\"login\" style=\"cursor:pointer ;width:225px; height:30px; border:0px; background: url(images/btnbg.gif); color:#056bb6; font-weight:bold; font-size:14px\" value=\"登&nbsp;录\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:100%; height:260px; background:#FFF\">\r\n");
      out.write("\t<div style=\"width:1024px; line-height:28px; margin-left:auto; margin-right:auto\">\r\n");
      out.write("      <div style=\"float:left; width:830px\">\r\n");
      out.write("        <p>办公地址：上海市吴中路686号东航金融中心6楼  邮编：201103  电话：021-64056666(总机)  传真：021-64068852 </p>\r\n");
      out.write("        <p> </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"float:right; background:url(images/gs.gif) no-repeat left center; width:194px; text-align:right\"><span><a href=\"#\">上海工商 沪ICP备05002999号</a></span></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("<div id=\"changepassworddialog\" title=\"<font style='color:#FFFFFF;font-size:14px;'>为了保证东航金融数据安全，请您修改默认密码</font>\">\r\n");
      out.write("\t<form action=\"changepwd.do?method=changePwd\" name=\"changePwdForm\" id=\"changePwdForm_id\">\r\n");
      out.write("\t\t\t<table id=\"querytable\" width=\"95%\" height=\"90%\" align=\"center\" style=\"font-size:13px;\">\r\n");
      out.write("\t\t \t\t<tr height=\"50%\">\r\n");
      out.write("\t\t \t\t\t<td width=\"100%\" align=\"center\" colspan=\"2\">\r\n");
      out.write("\t\t \t\t\t\t<table  width=\"100%\" height=\"50%\" align=\"center\" style=\"border:1px solid #a6c9e2;font-size:13px;\">\r\n");
      out.write("\t\t \t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t<td width=\"30%\" align=\"right\">旧密码\r\n");
      out.write("\t\t\t\t\t\t \t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t<td width=\"70%\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t \t\t\t\t<input type=\"password\"  id=\"oldpwd_id\" name=\"oldpwd\" style=\"height:20px;font-size:13px;\"/>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t<td width=\"30%\" align=\"right\">新密码\r\n");
      out.write("\t\t\t\t\t\t \t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t<td width=\"70%\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t \t\t\t\t<input type=\"password\"  id=\"newpwd_id\" name=\"newpwd\" style=\"height:20px;font-size:13px;\"/>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t\t<label style=\"color:#FF0000\">数字和字母的组合</label>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t<td width=\"30%\" align=\"right\">确认新密码\r\n");
      out.write("\t\t\t\t\t\t \t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t<td width=\"70%\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t \t\t\t\t<input type=\"password\"  id=\"cinfirmnewpwd_id\" name=\"cinfirmnewpwd\" style=\"height:20px;font-size:13px;\"/>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t<td align=\"center\" width=\"100%\" colspan=\"2\" >\r\n");
      out.write("\t\t\t\t\t\t \t\t\t\t<input  type=\"button\" value=\"修改\" id=\"btnsubmit_id\"/>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t\t<input  type=\"button\" value=\"重置\" id=\"btnreset_id\"/>\r\n");
      out.write("\t\t\t\t\t\t \t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t \t\t\t\t</table>  \r\n");
      out.write("\t\t \t\t\t</td>\r\n");
      out.write("\t\t \t\t</tr>\r\n");
      out.write(" \t\t\t</table>  \r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write(" \r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
